Repository sinProject-Inc/talk, pull requests merged in 2023-02, with the labels that each got.

#179 Set up vitest #178
  .vscode/settings.json
  package-lock.json
  package.json
  src/lib/api/api.test.ts
  src/lib/api/api_path.test.ts
  src/lib/app/app_setting_db.test.ts
  src/lib/auth/email.test.ts
  src/lib/auth/mail_subject.test.ts
  vite.config.ts
Labels: enhancement

#198 translate: Save translate history #180
  .vscode/settings.json
  e2e/translate.spec.ts
  src/lib/api/api_path.test.ts
  src/lib/api/api_path.ts
  src/lib/auth/email.test.ts
  src/lib/components/translate/translate_box.svelte
  src/lib/text/text_db.ts
  src/lib/text/text_limit.ts
  src/lib/text/texts_api.test.ts
  src/lib/text/texts_api.ts
  src/lib/text/valid_text.ts
  src/routes/api/text/[language_code]/+server.ts
  src/routes/translate/+page.svelte
Labels: enhancement, breaking-change

#200 Save translate history #180 translate: Delete from history #181 Make translation and main page locale the same #189
  .vscode/settings.json
  e2e/page.spec.ts
  e2e/translate.spec.ts
  src/lib/api/api_path.test.ts
  src/lib/api/api_path.ts
  src/lib/app/app.ts
  src/lib/components/confirm_delete_modal.svelte
  src/lib/components/icon_button.svelte
  src/lib/components/text_list_text.svelte
  src/lib/components/translate/translate_box.svelte
  src/lib/text/delete_text_api.test.ts
  src/lib/text/delete_text_api.ts
  src/lib/text/text_db.ts
  src/lib/text/text_limit.ts
  src/lib/text/texts_api.test.ts
  src/lib/text/texts_api.ts
  src/locales/en.json
  src/locales/ja.json
  src/locales/km.json
  src/locales/ko.json
  src/locales/zh-TW.json
  src/routes/+page.svelte
  src/routes/api/delete-text/[text_id]/+server.ts
  src/routes/api/text/[language_code]/+server.ts
  src/routes/translate/+page.svelte
Labels: enhancement

#273 Refactor the speech recognition class and speech html elements #272
  src/lib/components/translate/translate_box.svelte
  src/lib/speech/speech_element.ts
  src/lib/speech/speech_text_area_element.ts
  src/lib/speech/speech_text_element.ts
  src/lib/speech/web_speech.ts
  src/lib/speech/web_speech_recognition.ts
  src/routes/+page.svelte
Labels: breaking-change

#317 Create repository interfaces #316
  src/hooks.server.ts
  src/lib/app/app_setting_db.test.ts
  src/lib/app/app_setting_repository.ts
  src/lib/app/app_setting_repository_prisma.test.ts
  src/lib/app/app_setting_repository_prisma.ts
  src/lib/auth/auth_pin_repository.ts
  src/lib/auth/auth_pin_repository_prisma.ts
  src/lib/auth/auth_token_repository.ts
  src/lib/auth/auth_token_repository_prisma.ts
  src/lib/auth/life_time.ts
  src/lib/auth/signing.ts
  src/lib/auth/user_repository.ts
  src/lib/auth/user_repository_prisma.ts
  src/lib/language/language_repository.ts
  src/lib/language/language_repository_prisma.ts
  src/lib/language/locale_repository.ts
  src/lib/language/locale_repository_prisma.ts
  src/lib/speech/sound/sound_repository.ts
  src/lib/speech/sound/sound_repository_prisma.ts
  src/lib/text/text_repository.ts
  src/lib/text/text_repository_prisma.ts
  src/lib/translation/translation_repository.ts
  src/lib/translation/translation_repository_prisma.ts
  src/routes/api/add-text/[language_code]/[text]/+server.ts
  src/routes/api/add-translation/[text_id]/[language_code]/[translation]/+server.ts
  src/routes/api/delete-text/[text_id]/+server.ts
  src/routes/api/find-translation/[text_id]/[language_code]/+server.ts
  src/routes/api/languages/+server.ts
  src/routes/api/locales/+server.ts
  src/routes/api/text-to-speech/[text]/[locale_code]/+server.ts
  src/routes/api/text/[language_code]/+server.ts
  src/routes/pin-code/+page.server.ts
Labels: breaking-change

#352 Get version from package.json #345
  package.json
  src/routes/+page.svelte
  svelte.config.js
Labels: enhancement
